# LoadBalancer Service. Will only work on supported cloud platforms (AKS, EKS, GKE, DOK, IBM, LKE etc...)
# Listens externally on 80 (port) and forwards to Pod/container on 80 (targetPort)
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  selector:
    app: stg
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer