# LoadBalancer Service. Will only work on supported cloud platforms (AKS, EKS, GKE, DOK, IBM, LKE etc...)

apiVersion: v1
kind: Service
metadata:
  name: lb # Name of the service
spec:
  type: LoadBalancer
  selector:
    app: stg # The pods you need to expose so, matching pod labels should go here.
  ports:
    - protocol: TCP
      name: http
      port: 80 # Service port
      targetPort: 80 # Container port
      