apiVersion: v1
kind: Pod
metadata:
  name: web
spec:
  containers:
  - name: web-ctr
    image: nigelpoulton/nginxadapter:1.0
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
    ports:
    - containerPort: 80
  - name: transformer
    image: nginx/nginx-prometheus-exporter
    resources:
      limits:
        cpu: "200m"
        memory: "128Mi"
    args: ["-nginx.scrape-uri","http://localhost/nginx_status"]
    ports:
    - containerPort: 9113