apiVersion: v1
kind: Service
metadata:
  name: pluralsight-ftw #This causes the init container to break and move on to main container.
spec:
  selector:
    app: initializer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer