kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ps-az-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-file
volumeBindingMode: WaitForFirstConsumer
parameters:
  skuName: Standard_LRS #A new storage account of this SKU will automatically created in the same resource group as K8s.