apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: svc-ro
rules: #This role give ability to get/watch/list services in the default namespace.
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: svc-ro
  namespace: default
subjects:
- kind: ServiceAccount
  name: "service-reader" #Assiges the role to the "service-reader" service account.
  namespace: default
roleRef:
  kind: Role 
  name: svc-ro #Binds with the role above
  apiGroup: rbac.authorization.k8s.io